baseURL = 'https://mdyssr.vercel.app/'
disqusShortname = 'mdyssr'
languageCode = 'en-us'
theme = "hugo-tania"
title = 'Muhammad Yasser'

[params]
author = "Muhammad Yasser"
enableFootnotes = false
maxCategoryToShow = 10
siteDesc = "a Pride Speech blog"
siteName = "Muhammad Yasser's Blog"
titleLogo = "favicon.ico"

[params.colorScheme]
default = "dark"
toggle = true

[params.comments]
enabled = true
provider = "disqus"

[[menu.header]]
name = "Posts"
url = "/posts/"

[[menu.header]]
name = "About"
url = "/about/"

[[menu.footer]]
#name = "RSS"
#url = "/index.xml"

[markup.highlight]
lineNos = true
noClasses = false

[markup.goldmark.renderer]
unsafe = true

[markup.goldmark.extensions]


[outputs]
home = ["HTML", "RSS", "JSON"]

[params.socialOptions]
#email = "roktmy@gmail.com"
github = "https://github.com/mdyssr"
instagram = "https://instagram.com/md_yssr"
twitter = "https://twitter.com/mdyssr_"
